---
name: step security

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  step-security
    runs-on: ubuntu-latest
    permissions: # Required for workload identity auth and push the trivy results to GitHub
      contents: read
      id-token: write
      security-events: write
    steps:
      - name: Harden Runner
        if: runner.environment == 'github-hosted'
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit



